### ISSUE TITLE
Hostnames

### ISSUE THREAD

**Issue by jonathanjfshaw** [wunderio/drupal-project-k8s#30]
I'm a bit concerned about this approach to hostnames:
```
clusterDomain: "silta.wdr.io"
branchname: "default"
```
```
{{- define "drupal.domain" -}}
{{ regexReplaceAll "[^[:alnum:]]" .Values.branchname "-" | lower }}.{{ .Release.Namespace }}.{{ .Values.clusterDomain }}
{{- end -}}
```

It seems to unnecessarily bake in a particular use case:
1) it's doesn't seem to handle cases where you don't want subdomains at all e.g. possibly production
2) calling the subdomain 'branchname' is unnecessarily specific.

2 alternative possibilities:

**Option A**
```
#values.yml
domain:
  template: "{{ regexReplaceAll "[^[:alnum:]]" .Values.domain.branch "-" | lower }}.{{ .Release.Namespace }}.{{ .Values.domain.cluster }}"
  cluster: "silta.wdr.io"
  branch: "default"
``` 
```
#_helpers.tpl
{{- define "drupal.domain" -}}
{{ tpl .Values.domain.template . }}
{{- end -}}
```

**Option B**
Revert back to a single hostname value and put responsibility for domain name processing back onto the calling code.
